application: robandken-152410
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(.*\.(gif|png|jpg|jpeg|ico|js|css|woff|svg|eot|ttf|otf))
  static_files: \1
  upload: (.*\.(gif|png|jpg|jpeg|ico|js|css|woff|svg|eot|ttf|otf))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
